"""The bench reads what the `agentlab` library writes (SPEC.md 8.6): runs by `agentlab.run`, the map
each run carries, the facts as bench events, stories from trusted files, and `bench.record`.

The spans are generated by the library itself on every test run (tests/fixtures/agentlab/scenarios.py,
in the library's own environment), never checked in, so the bench is always tested against what the
library writes today.
"""
from __future__ import annotations

import base64
import copy
import json
import logging
import subprocess
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator
from starlette.testclient import TestClient

import bench.server as srv
from adapters import otlp
from bench import record

ROOT = Path(__file__).resolve().parents[1]
EVENT = Draft202012Validator(json.loads((ROOT / "schema/bench-event.schema.json").read_text()))
APP = "helpdesk-scenario"


@pytest.fixture(scope="session")
def lib(tmp_path_factory):
    """{scenario: {...}} plus the story file, written by the library (see the module docstring)."""
    out = tmp_path_factory.mktemp("agentlab")
    r = subprocess.run(["uv", "run", "--quiet", "--project", str(ROOT / "sdk/python"), "python",
                        str(ROOT / "tests/fixtures/agentlab/scenarios.py"), str(out)],
                       capture_output=True, text=True, timeout=300, cwd=ROOT)
    assert r.returncode == 0, r.stderr[-3000:]
    data = json.loads((out / "scenarios.json").read_text())
    data["_story"] = out / f"{APP}.story.js"
    return data


def ingest(batches, state=None):
    state = state or otlp.TraceState()
    return state, [e for b in batches for e in state.ingest(copy.deepcopy(b))]


def merged(batches):
    return {"resourceSpans": [rs for b in batches for rs in copy.deepcopy(b)["resourceSpans"]]}


def kinds(events):
    return [(e["node"], e["event_type"]) for e in events]


def spans_of(body):
    return [s for rs in body["resourceSpans"] for ss in rs["scopeSpans"] for s in ss["spans"]]


def attr(span, key):
    return next((a for a in span["attributes"] if a["key"] == key), None)


# ---- the adapter --------------------------------------------------------------------------------

def test_a_run_reads_as_bench_events(lib):
    state, evs = ingest(lib["answer"]["batches"])
    assert all(not list(EVENT.iter_errors(e)) for e in evs)
    assert {e["run_id"] for e in evs} == {"t1:aaaa0001"}
    assert [e["seq"] for e in evs] == list(range(len(evs)))
    assert kinds(evs) == [
        ("_run", "run_started"),
        ("retrieve", "step_started"), ("retrieve", "retrieval"), ("retrieve", "step_finished"),
        ("classify", "step_started"), ("classify", "llm_call"), ("classify", "decision"),
        ("classify", "check_result"), ("classify", "step_finished"),
        ("grounding_check", "step_started"), ("grounding_check", "check_result"), ("grounding_check", "step_finished"),
        ("respond", "step_started"), ("respond", "step_finished"),
        ("_run", "run_finished")]
    by = {e["event_type"]: e for e in evs}
    rs = by["run_started"]["data"]
    assert rs["map_hash"] == lib["answer"]["map_hash"] and rs["app"] == APP and rs["thread"] == "t1"
    assert rs["input"] == {"text": "How do I reset my password?"}
    assert {e.get("session_id") for e in evs} == {"sess-1"}
    assert by["decision"]["data"] == {"rationale": "The handbook covers password resets.", "confidence": 0.9, "cited": ["sec-1"]}
    ck = next(e for e in evs if e["event_type"] == "check_result" and e["data"]["name"] == "unsure")["data"]
    assert ck["state"] == "passed" and ck["words"] == {"passed": "Sure enough", "failed": "Sent to a person"}
    llm = by["llm_call"]
    assert llm["data"]["params"]["json_schema"]["properties"]["category"]["enum"] == ["answerable", "needs_write"]
    assert llm["data"]["input_tokens"] == 120 and llm["data"]["cache_read_tokens"] == 100
    # A model call and a search are content of their node's step, not steps of their own.
    steps = {e["node"]: e["step_id"] for e in evs if e["event_type"] == "step_started"}
    assert llm["step_id"] == steps["classify"] and by["retrieval"]["step_id"] == steps["retrieve"]
    assert by["retrieval"]["data"]["source"] == "handbook" and "stale_index" not in by["retrieval"]["data"]
    # a retriever's other numeric scores reach the event (a story may show them)
    hit = by["retrieval"]["data"]["hits"][0]
    assert hit["score"] == 0.9 and hit["bm25"] == 7.25 and "bm25" not in by["retrieval"]["data"]["hits"][1]
    rf = by["run_finished"]["data"]
    assert rf == {**rf, "status": "ok", "outcome": "answered", "output": {"reply": "Use the self-service portal."},
                  "baseline": "~10 minutes"}
    assert state.maps[rs["map_hash"]] == lib["answer"]["manifest"]
    assert state.take_maps() == [(rs["map_hash"], lib["answer"]["manifest"])] and state.take_maps() == []


def test_the_map_arrives_first_and_the_run_span_last(lib):
    """One POST per span, in the order spans end (the exporter's order): the run opens on the
    manifest span with its map; the input arrives with the run span as run_updated."""
    batches = lib["answer_split"]["batches"]
    state = otlp.TraceState()
    first = state.ingest(copy.deepcopy(batches[0]))
    assert kinds(first) == [("_run", "run_started")]
    assert first[0]["data"]["map_hash"] == lib["answer"]["map_hash"]
    rest = [e for b in batches[1:] for e in state.ingest(copy.deepcopy(b))]
    whole = ingest(lib["answer"]["batches"])[1]
    assert sorted(kinds(first + rest)) == sorted(kinds(whole) + [("_run", "run_updated")])
    upd = next(e for e in rest if e["event_type"] == "run_updated")
    assert upd["data"] == {"input": {"text": "How do I reset my password?"}}
    assert [e["seq"] for e in first + rest] == list(range(len(first + rest)))


def test_a_run_span_whose_parent_never_arrives_is_still_the_run(lib):
    body = lib["foreign_parent"]["batches"][0]
    run_span = next(s for s in spans_of(body) if attr(s, "agentlab.kind")["value"]["stringValue"] == "run")
    assert run_span.get("parentSpanId"), "the scenario must give the run span a parent the bench never sees"
    evs = ingest([body])[1]
    assert kinds(evs)[0] == ("_run", "run_started") and kinds(evs)[-1] == ("_run", "run_finished")
    assert sum(e["event_type"] == "run_started" for e in evs) == 1


def test_redacted_content_is_never_labelled_full(lib):
    evs = ingest(lib["redacted"]["batches"])[1]
    assert {e["content_mode"] for e in evs} == {"redacted"}


def test_a_gate_is_one_step_across_the_pause_and_the_resume(lib):
    pause, resume = lib["gate"]["batches"]
    state = otlp.TraceState()
    a = state.ingest(copy.deepcopy(pause))
    assert ("_run", "run_finished") not in kinds(a), "a paused run isn't finished"
    assert kinds(a)[-1] == ("approval_gate", "gate_waiting"), "the gate's step stays open"
    assert state.run_info("t2:bbbb0002")["status"] == "paused"
    b = state.ingest(copy.deepcopy(resume))
    evs = a + b
    assert sum(e["event_type"] == "run_started" for e in evs) == 1
    gate = [e for e in evs if e["node"] == "approval_gate"]
    assert [e["event_type"] for e in gate] == ["step_started", "gate_waiting", "gate_resolved", "step_finished"]
    assert len({e["step_id"] for e in gate}) == 1
    assert next(e for e in gate if e["event_type"] == "gate_resolved")["data"] == {"approved": True, "by": "Dana (IT lead)"}
    assert ("execute_action", "ticket_opened") in kinds(b)
    assert kinds(b)[-1] == ("_run", "run_finished") and b[-1]["data"]["outcome"] == "executed"
    assert [e["seq"] for e in evs] == list(range(len(evs)))


def test_a_resume_in_a_new_process_joins_its_paused_run(lib):
    pause, resume = lib["gate_new_process"]["batches"]
    state, evs = ingest([pause, resume])
    assert {e["run_id"] for e in evs} == {"t3:cccc0003"}
    gate = [e for e in evs if e["node"] == "approval_gate"]
    assert [e["event_type"] for e in gate] == ["step_started", "gate_waiting", "gate_resolved", "step_finished"]
    assert state.run_info("t3:dddd0004")["id"] == "t3:cccc0003"
    # A fresh run on the same thread after that is its own run.
    other = copy.deepcopy(lib["answer"]["batches"][0])
    assert {e["run_id"] for e in state.ingest(other)} == {"t1:aaaa0001"}


def test_a_stale_index_is_flagged_on_the_search(lib):
    evs = ingest(lib["stale_index"]["batches"])[1]
    ret = next(e for e in evs if e["event_type"] == "retrieval")["data"]
    assert ret["stale_index"] is True and len(ret["corpus_hash"]) == 64


def test_another_instrumentors_span_stamped_with_a_node_joins_that_node(lib):
    body = lib["stamped"]["batches"][0]
    foreign = next(s for s in spans_of(body) if s["name"] == "ChatAnthropic")
    assert attr(foreign, "agentlab.node")["value"]["stringValue"] == "classify"
    evs = ingest([body])[1]
    assert kinds(evs) == [("_run", "run_started"), ("classify", "step_started"), ("classify", "llm_call"),
                          ("classify", "step_finished"), ("_run", "run_finished")]
    assert {e["run_id"] for e in evs} == {"t5:eeee0005"}


def _manifest_attr(body):
    span = next(s for s in spans_of(body) if attr(s, "agentlab.kind")["value"]["stringValue"] == "manifest")
    return attr(span, "agentlab.manifest")["value"]


@pytest.mark.parametrize("damage", ["truncated", "altered", "not_a_map"])
def test_a_damaged_map_is_refused_never_half_used(lib, damage):
    body = copy.deepcopy(lib["answer"]["batches"][0])
    v = _manifest_attr(body)
    if damage == "truncated":    # what OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT does
        v["stringValue"] = v["stringValue"][: len(v["stringValue"]) // 2]
    elif damage == "altered":
        v["stringValue"] = v["stringValue"].replace("Helpdesk (scenario)", "Helpdesk (edited)")
    else:
        v["stringValue"] = "[1, 2]"
    state, evs = ingest([body])
    rs = evs[0]["data"]
    assert "map_hash" not in rs and rs["map_error"].startswith("R13: ")
    assert state.take_maps() == [] and not state.maps
    # The run itself still shows: steps and facts don't depend on the map.
    assert ("classify", "decision") in kinds(evs) and kinds(evs)[-1] == ("_run", "run_finished")


def test_a_map_valid_by_hash_but_not_a_bench_map_is_refused():
    manifest = {"v": "bench-topology/0", "app": {"id": "BAD ID", "name": "x"}, "nodes": [], "edges": []}
    raw = otlp.canonical(manifest).decode()
    m, h, err = otlp.verify_manifest(raw, otlp.sha256_hex(manifest))
    assert m is None and "not a valid bench map" in err
    m, h, err = otlp.verify_manifest(raw, None)
    assert m is None and "doesn't match its hash" in err


def test_json_and_protobuf_give_the_same_ids(lib):
    """`to_otlp_json` writes protobuf's JSON mapping (base64 ids); exporters send protobuf."""
    from google.protobuf.json_format import ParseDict
    from opentelemetry.proto.collector.trace.v1.trace_service_pb2 import ExportTraceServiceRequest
    body = lib["answer"]["batches"][0]
    via_json = ingest([body])[1]
    pb = ParseDict(copy.deepcopy(body), ExportTraceServiceRequest()).SerializeToString()
    via_pb = otlp.TraceState().ingest(otlp.decode_protobuf(pb))
    assert [(e["event_type"], e.get("step_id")) for e in via_json] == [(e["event_type"], e.get("step_id")) for e in via_pb]
    assert all(len(e["step_id"]) == 16 for e in via_json if e.get("step_id"))
    assert otlp._norm_id(base64.b64encode(bytes.fromhex("ab" * 8)).decode(), 8) == "ab" * 8
    assert otlp._norm_id("AB" * 8, 8) == "ab" * 8
    assert otlp._norm_id("r1", 8) == "r1"


def test_level0_node_aliases_group_spans_under_their_langgraph_node():
    span = {"traceId": "1" * 32, "spanId": "ab" * 8, "name": "ChatOpenAI", "startTimeUnixNano": "1",
            "endTimeUnixNano": "2", "attributes": []}
    for key in ("agentlab.node", "langsmith.metadata.langgraph_node", "langfuse.observation.metadata.langgraph_node"):
        assert otlp.node_id(span, {key: "classify", "gen_ai.operation.name": "chat"}) == "classify"
    assert otlp.node_id(span, {"gen_ai.operation.name": "chat"}) == "chat"
    # OpenInference (its metadata JSON) and OpenLLMetry; the checkpoint namespace wins when present.
    meta = json.dumps({"langgraph_node": "inner", "langgraph_checkpoint_ns": "sub:1f2e|inner:9c8d"})
    assert otlp.node_id(span, {"metadata": meta}) == "sub/inner"
    assert otlp.node_id(span, {"metadata": json.dumps({"langgraph_node": "classify"})}) == "classify"
    assert otlp.node_id(span, {"traceloop.association.properties.langgraph_node": "classify"}) == "classify"
    assert otlp.node_id(span, {"traceloop.association.properties.langgraph_checkpoint_ns": "classify:ab12"}) == "classify"
    assert otlp.node_id(span, {"metadata": "not json", "gen_ai.operation.name": "chat"}) == "chat"
    # A map's node_from still wins.
    assert otlp.node_id(span, {"agentlab.node": "classify"}, {"span_name": True}) == "ChatOpenAI"


def test_the_apps_own_span_around_a_run_is_not_a_second_run(lib):
    """Shared provider: the app's HTTP span (no agentlab.run, not AI work) is in the run's trace."""
    body = copy.deepcopy(lib["answer"]["batches"][0])
    tid = spans_of(body)[0]["traceId"]
    body["resourceSpans"][0]["scopeSpans"].append({"spans": [
        {"traceId": tid, "spanId": base64.b64encode(b"\x01" * 8).decode(), "name": "POST /slack/events",
         "startTimeUnixNano": "1", "endTimeUnixNano": "9" * 19, "attributes": [], "status": {}},
        {"traceId": tid, "spanId": base64.b64encode(b"\x02" * 8).decode(), "name": "chat other",
         "startTimeUnixNano": "1", "endTimeUnixNano": "2",
         "attributes": [{"key": "gen_ai.operation.name", "value": {"stringValue": "chat"}}], "status": {}}]})
    evs = ingest([body])[1]
    assert {e["run_id"] for e in evs} == {"t1:aaaa0001"}
    assert sum(e["event_type"] == "run_started" for e in evs) == 1
    assert ("chat", "llm_call") in kinds(evs), "an unstamped AI span in the trace joins the run"
    assert not any(e["node"] == "POST /slack/events" for e in evs)


def test_app_events_cannot_forge_run_or_step_boundaries():
    assert otlp._agentlab_fact("agentlab.event", {"agentlab.event.type": "run_finished",
                                                  "agentlab.event.data": "{}"}) is None
    assert otlp._agentlab_fact("agentlab.event", {"agentlab.event.type": "permission_verdict",
                                                  "agentlab.event.data": '{"allowed": true}'}) == ("permission_verdict", {"allowed": True})
    assert otlp._agentlab_fact("agentlab.check", {"agentlab.check.name": "x"}) is None  # no verdict, no check


# ---- through the real LangGraph integration ----------------------------------------------------------

def _needs(lib, name):
    if name not in lib:
        pytest.skip("agentlab.langgraph or LangGraph isn't installed in the library's environment")
    return lib[name]


def test_the_langgraph_quickstart_reads_as_its_graph(lib):
    state, evs = ingest(_needs(lib, "lg_quickstart")["batches"])
    assert all(not list(EVENT.iter_errors(e)) for e in evs)
    assert len({e["run_id"] for e in evs}) == 1
    rs = evs[0]["data"]
    assert evs[0]["event_type"] == "run_started" and rs["app"] == "support-assistant" and rs["map_hash"]
    manifest = state.maps[rs["map_hash"]]
    on_map = {n["id"] for n in manifest["nodes"]}
    ran = [e["node"] for e in evs if e["event_type"] == "step_started"]
    assert ran and set(ran) <= on_map, "every step is a node of the graph's own map"
    steps = {e["step_id"]: e["node"] for e in evs if e["event_type"] == "step_started"}
    for e in evs:
        if e["event_type"] in ("llm_call", "retrieval", "decision", "check_result"):
            assert steps.get(e["step_id"]) == e["node"], f"{e['event_type']} on {e['node']} isn't on its node's step"
    assert any(e["event_type"] == "llm_call" for e in evs) and evs[-1]["event_type"] == "run_finished"


def test_a_real_interrupt_is_one_gate_step(lib):
    pause, resume = _needs(lib, "lg_gate")["batches"]
    state = otlp.TraceState()
    a = state.ingest(copy.deepcopy(pause))
    assert not any(e["event_type"] == "run_finished" for e in a)
    rid = a[0]["run_id"]
    assert state.run_info(rid)["status"] == "paused"
    b = state.ingest(copy.deepcopy(resume))
    assert {e["run_id"] for e in b} == {rid} and not any(e["event_type"] == "run_started" for e in b)
    gate = [e for e in a + b if e["node"] == "gate"]
    assert [e["event_type"] for e in gate] == ["step_started", "gate_waiting", "gate_resolved", "step_finished"]
    assert len({e["step_id"] for e in gate}) == 1
    assert gate[1]["data"]["proposed"] == {"action_type": "create_ticket", "title": "Access to Compass"}
    assert b[-1]["event_type"] == "run_finished" and b[-1]["data"]["outcome"] == "executed"
    # The branch taken is derived from what ran next; the map has it.
    edges = state.maps[a[0]["data"]["map_hash"]]["edges"]
    assert {"from": "gate", "to": "act", "from_branch": "approved"} in [
        {k: e[k] for k in ("from", "to", "from_branch") if k in e} for e in edges]


# ---- the server -----------------------------------------------------------------------------------

@pytest.fixture
def c(tmp_path, monkeypatch):
    monkeypatch.setattr(srv, "LOG_DIR", tmp_path / "log")
    monkeypatch.setattr(srv, "APPS_DIR", tmp_path / "apps")
    monkeypatch.setattr(srv, "MAPS_DIR", tmp_path / "maps")

    def reset():
        srv.store.events.clear()
        srv.store.run_app.clear()
        srv.store.maps.clear()
        srv.store.app_map.clear()
        srv.store.run_map.clear()
        srv.store.story_files = {}
        srv.store.otlp = otlp.TraceState()
        srv.store.load_apps()

    reset()
    yield TestClient(srv.app)
    reset()


def test_the_bench_keeps_and_serves_each_runs_map(c, lib, tmp_path):
    h = lib["answer"]["map_hash"]
    assert c.post("/v1/traces", json=lib["answer"]["batches"][0]).status_code == 200
    assert c.get(f"/maps/{h}").json() == lib["answer"]["manifest"]
    assert json.loads((tmp_path / "maps" / f"{h}.json").read_text()) == lib["answer"]["manifest"]
    assert c.get("/maps/" + "0" * 64).status_code == 404
    assert c.get("/maps/not-a-hash").status_code == 404
    # The existing viewer asks for an app's map: it gets the one its latest run carried.
    assert c.get(f"/topology/{APP}").json() == lib["answer"]["manifest"]
    assert c.get("/topologies").json() == [{"id": APP, "name": "Helpdesk (scenario)", "story": False, "map_hash": h}]
    run = c.get("/runs").json()[0]
    assert run["map_hash"] == h and run["app"] == APP and run["status"] == "ok"
    # A restarted bench reads the map from disk, and checks it again.
    srv.store.maps.clear()
    assert c.get(f"/maps/{h}").json() == lib["answer"]["manifest"]
    srv.store.maps.clear()
    (tmp_path / "maps" / f"{h}.json").write_text(json.dumps({**lib["answer"]["manifest"], "never": ["edited"]}))
    assert c.get(f"/maps/{h}").status_code == 404


def test_put_apps_is_still_accepted_and_a_runs_own_map_wins(c, lib, caplog):
    head = json.loads((ROOT / "examples/hello-answer.recording.jsonl").read_text().splitlines()[0])
    declared = copy.deepcopy(head["topology"])
    declared["app"]["id"] = APP
    assert c.put(f"/apps/{APP}", json={"topology": declared, "story": None}).json()["ok"] is True
    assert c.get(f"/topology/{APP}").json() == declared
    with caplog.at_level(logging.INFO, logger="bench.server"):
        c.post("/v1/traces", json=lib["answer"]["batches"][0])
    assert any("carry their own maps" in r.message for r in caplog.records)
    assert c.get(f"/topology/{APP}").json() == lib["answer"]["manifest"]
    caplog.clear()
    with caplog.at_level(logging.INFO, logger="bench.server"):
        assert c.put(f"/apps/{APP}", json={"topology": declared, "story": None}).status_code == 200
    assert any("used only for runs that don't" in r.message for r in caplog.records)


def test_a_story_is_served_only_from_a_trusted_file_with_the_runs_hash(c, lib, tmp_path):
    c.post("/v1/traces", json=lib["answer"]["batches"][0])
    want = lib["answer"]["manifest"]["story"]["sha256"]
    r = c.get(f"/apps/{APP}/story.js")
    assert r.status_code == 404 and "AGENT_LAB_STORIES" in r.headers["x-agent-lab-story"]
    srv.store.story_files = srv.trusted_stories(f"{APP}={lib['_story']}")
    r = c.get(f"/apps/{APP}/story.js")
    assert r.status_code == 200 and "BenchStory.register" in r.text
    assert c.get(f"/apps/{APP}/story.js?sha256={want}").status_code == 200
    assert c.get(f"/topologies").json()[0]["story"] is True
    changed = tmp_path / "changed.js"
    changed.write_text(lib["_story"].read_text() + "// edited\n")
    srv.store.story_files = {APP: changed}
    r = c.get(f"/apps/{APP}/story.js")
    assert r.status_code == 404 and r.headers["x-agent-lab-story"] == "story file differs from the one this run was built with"
    assert c.get(f"/apps/{APP}/story.js?sha256={'f' * 64}").status_code == 404


def test_trusted_stories_parsing(tmp_path):
    got = srv.trusted_stories(f"a={tmp_path}/a.js; b = {tmp_path}/b.js ;bogus;")
    assert got == {"a": tmp_path / "a.js", "b": tmp_path / "b.js"}


def test_stream_filters_library_runs_by_app_and_session(c, lib):
    c.post("/v1/traces", json=lib["answer"]["batches"][0])
    assert srv.store.backlog("sess-1", APP) and not srv.store.backlog("sess-1", "other-app")
    assert not srv.store.backlog("other-session", APP)


# ---- bench.record -----------------------------------------------------------------------------------

def test_record_writes_one_self_contained_recording_per_run(lib, tmp_path):
    src = tmp_path / "gate.otlp.json"
    src.write_text(json.dumps(merged(lib["gate"]["batches"])))
    assert record.main(["--otlp", str(src), "--out", str(tmp_path / "out"), "--name", "req-011-approved",
                        "--title", "Asks for access", "--group", "It opens a ticket", "--t0", "1790696431.28",
                        "--regen-id", "abc123"]) == 0
    rows = [json.loads(l) for l in (tmp_path / "out/req-011-approved.recording.jsonl").read_text().splitlines()]
    head, evs = rows[0], rows[1:]
    assert head["v"] == "bench-recording/0" and head["title"] == "Asks for access" and head["regen_id"] == "abc123"
    assert head["topology"]["app"]["id"] == APP and head["story"] is None
    assert all(not list(EVENT.iter_errors(e)) for e in evs)
    assert [e["event_type"] for e in evs].count("run_started") == 1 and "run_updated" not in [e["event_type"] for e in evs]
    assert evs[0]["data"]["input"] == {"text": "Give me access to Compass"}
    assert {e["run_id"] for e in evs} == {"req-011-approved"} and {e["session_id"] for e in evs} == {"recording"}
    assert evs[0]["ts"] == 1790696431.28 and [e["seq"] for e in evs] == list(range(len(evs)))
    assert {e["step_id"] for e in evs if e["node"] == "approval_gate"} == {"req-011-approved:approval_gate:1"}
    assert not any("parent_step_id" in e for e in evs)


def test_record_is_stable_across_regenerations(lib, tmp_path):
    """Two library passes of the same run differ in span ids and clock; their recordings don't."""
    a = record.record(merged(lib["answer"]["batches"]), name="x", t0=1000.0,
                      stories={APP: lib["_story"]})[0][1]
    b = record.record(merged(lib["foreign_parent"]["batches"]), name="x", t0=1000.0)[0][1]
    strip = lambda rows: [(e["node"], e["event_type"], e.get("step_id")) for e in rows[1:]]
    assert strip(a) == strip(b)


def test_record_refuses_a_missing_or_different_story_and_a_damaged_map(lib, tmp_path):
    body = merged(lib["answer"]["batches"])
    with pytest.raises(record.RecordError, match="AGENT_LAB_STORIES"):
        record.record(body, name="x")
    other = tmp_path / "other.js"
    other.write_text("// not the story\n")
    with pytest.raises(record.RecordError, match="differs"):
        record.record(body, name="x", stories={APP: other})
    rows = record.record(body, name="x", stories={APP: lib["_story"]})[0][1]
    assert rows[0]["story"] == lib["_story"].read_text()
    bad = copy.deepcopy(lib["answer"]["batches"][0])
    _manifest_attr(bad)["stringValue"] = _manifest_attr(bad)["stringValue"][:100]
    with pytest.raises(record.RecordError, match="R13"):
        record.record(bad, name="x", stories={APP: lib["_story"]})
    src = tmp_path / "bad.json"
    src.write_text(json.dumps(bad))
    assert record.main(["--otlp", str(src), "--out", str(tmp_path / "o"), "--name", "x"]) == 1
    assert not (tmp_path / "o").exists()


def test_record_names_several_runs_apart(lib):
    body = merged(lib["redacted"]["batches"] + lib["stamped"]["batches"])
    files = record.record(body, name="pair")
    assert [stem for stem, _ in files] == ["pair-1", "pair-2"]


# ---- through the viewer's own logic -------------------------------------------------------------------

def _viewer(recording_rows, tmp_path):
    """Runs viewer/logic.js (the code the viewer runs) over a recording: its map checks and sources."""
    p = tmp_path / "rec.jsonl"
    p.write_text("".join(json.dumps(r) + "\n" for r in recording_rows))
    script = """
      import * as L from '%s';
      import fs from 'node:fs';
      const rows = fs.readFileSync(process.argv[1], 'utf8').split('\\n').filter(Boolean).map(JSON.parse);
      const topo = rows[0].topology, events = L.sortEvents(rows.slice(1).map(L.normalizeEvent));
      const run = L.newRun('r'); events.forEach((e) => L.reduce(run, e, 0));
      console.log(JSON.stringify({checks: L.mapChecks(topo, events), sources: L.sourceStates(topo, events)
        .map((s) => ({id: s.id, line: L.sourceCountsLine(s), givenKnown: s.givenKnown})),
        rows: L.checkStates(topo, events, true).map((r) => r.line), baseline: L.baselineOf(events, topo),
        outcome: L.outcome(topo, events).text, hash: L.runMapHash(events), input: run.input}));
    """ % (ROOT / "viewer/logic.js").as_uri()
    r = subprocess.run(["node", "--input-type=module", "-e", script, str(p)], capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, r.stderr
    return json.loads(r.stdout)


def test_viewer_logic_reads_a_library_run(lib, tmp_path):
    rows = record.record(merged(lib["answer"]["batches"]), name="x", stories={APP: lib["_story"]})[0][1]
    v = _viewer(rows, tmp_path)
    assert [f["code"] for f in v["checks"] if f["from"] == "run"] == []
    assert {f["code"] for f in v["checks"]} <= {"R12"}, "the scenario's map has words missing (info), nothing else"
    assert v["sources"] == [{"id": "handbook", "line": "3 available · 1 given to the AI · 1 relied on", "givenKnown": True}]
    assert "✓ Sure enough." in v["rows"]
    assert v["baseline"] == "~10 minutes" and v["outcome"] == "Answered"
    assert v["hash"] == lib["answer"]["map_hash"] and v["input"] == {"text": "How do I reset my password?"}


def test_viewer_logic_flags_what_a_bad_run_reports(lib, tmp_path):
    rows = record.record(merged(lib["bad_facts"]["batches"]), name="x")[0][1]
    checks = _viewer(rows, tmp_path)["checks"]
    assert any(f["code"] == "R8" and f["branch"] == "no_such_branch" for f in checks)
    assert any(f["code"] == "R9" and "sec-9" in f["message"] for f in checks)
    rows = record.record(merged(lib["stale_index"]["batches"]), name="x")[0][1]
    assert any(f["code"] == "R9" and "stale index" in f["message"] for f in _viewer(rows, tmp_path)["checks"])
    rows = record.record(merged(lib["redacted"]["batches"]), name="x")[0][1]
    src = _viewer(rows, tmp_path)["sources"][0]
    assert src["givenKnown"] is False and "not known" in src["line"]
